name: Continuous Integration

on:
  pull_request_target:
    branches:
      - master
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v2.1.5
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Format
        run: npm run format
    timeout-minutes: 5
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v2.1.5
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Lint
        run: npm run lint
    timeout-minutes: 5
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v2.1.5
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Spellcheck
        run: npm run spellcheck
    timeout-minutes: 5
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v2.1.5
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Test
        run: npm run test:ci
      - name: Upload coverage to Coveralls
        uses: mad-it/coveralls-github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          git-branch: ${{ github.event.pull_request.head.ref || github.ref }}
          git-commit: ${{ github.event.pull_request.head.sha || github.sha }}
    timeout-minutes: 5
  types:
    name: Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v2.1.5
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Types
        run: npm run types
    timeout-minutes: 5
  prerelease:
    name: Pre-release
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v2.1.5
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Cache local cache
        uses: actions/cache@v2.1.5
        with:
          key: local-${{ github.sha }}
          path: .cache
          restore-keys: |
            local-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Build
        run: npm run build
      - name: Version
        run: |
          npm version prerelease \
            --commit-hooks=false \
            --git-tag-version=false \
            --preid="${GITHUB_SHA::7}"
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Publish to GitHub Packages
        run: npm publish --tag="dev"
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@ridedott'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        name: Publish to npm
        run: npm publish --tag="dev"
    timeout-minutes: 5
  merge-me:
    name: Merge me!
    needs:
      - format
      - lint
      - spellcheck
      - test
      - types
      - prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.DOTTBOTT_TOKEN }}
    timeout-minutes: 5
