name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history.
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v2.1.6
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Build
        run: npm run build
      - env:
          GITHUB_TOKEN: ${{ secrets.DOTTBOTT_TOKEN }}
        id: release
        name: Release
        uses: ridedott/release-me-action@v3.6.10
        with:
          node-module: true
          release-rules: |
            [
              { "release": "patch", "type": "build" },
              { "release": "patch", "type": "chore" },
              { "release": "patch", "scope": "deps-dev", "subject": "bump typescript*", "type": "chore" },
              { "release": "patch", "type": "ci" },
              { "release": "patch", "type": "docs" },
              { "release": "patch", "type": "improvement" },
              { "release": "patch", "type": "refactor" },
              { "release": false, "scope": "deps-dev", "type": "chore" },
              { "release": false, "subject": "*\\[skip release\\]*" }
            ]
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.release.outputs.released == 'true'
        name: Publish to GitHub Packages
        run: npm publish
      - if: steps.release.outputs.released == 'true'
        name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@ridedott'
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: steps.release.outputs.released == 'true'
        name: Publish to npm
        run: npm publish
      - if: steps.release.outputs.released == 'true'
        name: Output
        run: |
          echo released version: ${{ steps.release.outputs.version }}, type: ${{ steps.release.outputs.level }}
    timeout-minutes: 5
