name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history.
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v2.1.4
        with:
          key: npm-${{ hashFiles('./package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-
      - name: Install dependencies
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline
      - name: Build
        run: npm run build
      - name: Release
        # Prevent version bumps of @ridedott/eslint-config from triggering a release.
        if:
          contains(github.event.commits[0].message, 'chore(deps-dev)&#58; bump
          @ridedott/eslint-config') == false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_DOTTBOTT }}
        id: build_package
        uses: ridedott/release-me-action@master
        with:
          node-module: true
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: steps.build_package.outputs.released == 'true'
        run: npm publish
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
        with:
          registry-url: 'https://registry.npmjs.org'
          scope: '@ridedott'
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        if: steps.build_package.outputs.released == 'true'
        run: npm publish
      - name: Output
        if: steps.build_package.outputs.released == 'true'
        run: |
          echo released version: ${{ steps.build_package.outputs.version }}, type: ${{ steps.build_package.outputs.level }}
    timeout-minutes: 5
